# Generated by Django 2.2.6 on 2019-10-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0003_auto_20191012_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='przecena',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='nazwa',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='wydanie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
