# Generated by Django 2.2.6 on 2019-10-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0004_auto_20191012_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='gatunek',
            field=models.CharField(max_length=30),
        ),
    ]
