# Generated by Django 2.2.6 on 2019-10-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0005_auto_20191012_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=400),
        ),
    ]
