# Generated by Django 2.2.6 on 2019-10-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0007_book_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='wydanie',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
