# Generated by Django 2.2.6 on 2019-10-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0008_auto_20191012_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='wydanie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='zdjecie',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
