# Generated by Django 2.2.6 on 2019-10-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0012_auto_20191013_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='opis',
            field=models.TextField(),
        ),
    ]
