# Generated by Django 2.2.6 on 2019-10-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0013_auto_20191013_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_stron', models.IntegerField(default=0)),
                ('ocena', models.IntegerField(choices=[(1, 'Słaba'), (0, 'Nieznany'), (4, 'Bardzo dobra'), (5, 'Arcydzieło'), (3, 'Dobra'), (2, 'Średnia')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='biblioteka.ExtraInfo'),
            preserve_default=False,
        ),
    ]
