# Generated by Django 2.2.6 on 2019-10-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0014_auto_20191020_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='ocena',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (3, 'Dobra'), (1, 'Słaba'), (5, 'Arcydzieło'), (4, 'Bardzo dobra'), (2, 'Średnia')], default=0),
        ),
    ]
