# Generated by Django 2.2.6 on 2019-10-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0015_auto_20191020_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='ocena',
            field=models.IntegerField(choices=[(1, 'Słaba'), (0, 'Nieznany'), (2, 'Średnia'), (4, 'Bardzo dobra'), (5, 'Arcydzieło'), (3, 'Dobra')], default=False),
        ),
    ]
