# Generated by Django 2.2.6 on 2019-10-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0017_auto_20191020_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrainfo',
            old_name='ilosc_stron',
            new_name='czas_trwania',
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='ocena',
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(3, 'Dobra'), (4, 'Bardzo dobra'), (2, 'Średnia'), (1, 'Słaba'), (0, 'Nieznany')], default=0),
        ),
    ]
