# Generated by Django 2.2.6 on 2019-10-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0020_auto_20191020_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='info',
        ),
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='ocena',
            field=models.IntegerField(choices=[(5, 'Arcydzieło'), (1, 'Słaba'), (4, 'Bardzo dobra'), (3, 'Dobra'), (2, 'Średnia'), (0, 'Nieznany')], default=0),
        ),
    ]
