# Generated by Django 2.2.6 on 2019-10-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0021_auto_20191020_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='biblioteka.ExtraInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='ocena',
            field=models.IntegerField(choices=[(1, 'Słaba'), (0, 'Nieznany'), (3, 'Dobra'), (2, 'Średnia'), (4, 'Bardzo dobra'), (5, 'Arcydzieło')], default=0),
        ),
    ]
