# Generated by Django 2.2.6 on 2019-10-20 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0022_auto_20191020_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.ExtraInfo'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='ocena',
            field=models.IntegerField(choices=[(2, 'Średnia'), (1, 'Słaba'), (5, 'Arcydzieło'), (3, 'Dobra'), (4, 'Bardzo dobra'), (0, 'Nieznany')], default=0),
        ),
    ]
