# Generated by Django 2.2.6 on 2019-10-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0023_auto_20191020_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='biblioteka.ExtraInfo'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='ocena',
            field=models.IntegerField(choices=[(4, 'Bardzo dobra'), (5, 'Arcydzieło'), (0, 'Nieznany'), (3, 'Dobra'), (2, 'Średnia'), (1, 'Słaba')], default=0),
        ),
    ]
