# Generated by Django 2.2.6 on 2019-10-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0024_auto_20191020_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='ocena',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (4, 'Bardzo dobra'), (1, 'Słaba'), (2, 'Średnia'), (5, 'Arcydzieło'), (3, 'Dobra')], default=0),
        ),
    ]
