# Generated by Django 2.2.6 on 2019-10-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0025_auto_20191020_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='info',
        ),
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='ksiazki',
            field=models.ManyToManyField(to='biblioteka.Book'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='ocena',
            field=models.IntegerField(choices=[(2, 'Średnia'), (3, 'Dobra'), (0, 'Nieznany'), (4, 'Bardzo dobra'), (5, 'Arcydzieło'), (1, 'Słaba')], default=0),
        ),
    ]
