# Generated by Django 2.2.6 on 2019-10-21 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0026_auto_20191020_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='ksiazki',
        ),
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='biblioteka.ExtraInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='ocena',
            field=models.IntegerField(choices=[(5, 'Arcydzieło'), (0, 'Nieznany'), (2, 'Średnia'), (3, 'Dobra'), (1, 'Słaba'), (4, 'Bardzo dobra')], default=0),
        ),
    ]
