# Generated by Django 2.2.6 on 2019-10-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0027_auto_20191021_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.ExtraInfo'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='ocena',
            field=models.IntegerField(choices=[(4, 'Bardzo dobra'), (3, 'Dobra'), (2, 'Średnia'), (5, 'Arcydzieło'), (0, 'Nieznany'), (1, 'Słaba')], default=0),
        ),
    ]
