# Generated by Django 2.2.6 on 2019-10-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0028_auto_20191021_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='info',
        ),
        migrations.DeleteModel(
            name='ExtraInfo',
        ),
    ]
