# Generated by Django 2.2.6 on 2019-10-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0030_auto_20191022_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='zdjecie',
            field=models.ImageField(null=True, upload_to='zdjecia_ksiazek'),
        ),
    ]
