# Generated by Django 2.2.6 on 2019-11-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0032_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
                ('opis', models.TextField()),
            ],
        ),
    ]
